config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'drinks#index'

  post '/advanced-filter', to: 'drinks#advanced_filter', as: 'advanced_filter'
  get '/advanced-filter', to: 'drinks#advanced_filter'

  post '/filter', to: 'drinks#simple_filter', as: 'simple_filter'
  get '/filter', to: 'drinks#simple_filter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, :description, :image_url, presence: true
  validates :rating_avg, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :alcohol_level, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  # Bitterness level
  validates :ibu, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

  enum temperature: %i[
    hot
    warm
    ambient
    cold
    extra_cold
  ]

  def self.simple_filter(filters)
    drinks = self.unscoped
    unless filters[:search].blank?
      drinks = drinks.where('(name ILIKE :q OR
        base_ingredient ILIKE :q OR
        description ILIKE :q OR
        drinkware ILIKE :q OR
        origin ILIKE :q)', q: "%#{filters[:search]}%")
    end
    drinks.order(:name)
  end

  def self.advanced_filter(filters)
    drinks = self.unscoped
    unless filters[:base_ingredient].blank?
      drinks = drinks.where('(name ILIKE :q OR base_ingredient ILIKE :q OR description ILIKE :q)', q: "%#{filters[:base_ingredient]}%")
    end

    unless filters[:drinkware].blank?
      drinks = drinks.where('drinkware ILIKE :q', q: "%#{filters[:drinkware]}%")
    end

    unless filters[:origin].blank?
      drinks = drinks.where('origin ILIKE :q', q: "%#{filters[:origin]}%")
    end

    unless filters[:distilled].blank?
      drinks = drinks.where(distilled: filters[:distilled])
    end

    unless filters[:alcohol_level].blank?
      drinks = drinks.where(alcohol_level: filters[:alcohol_level])
    end

    unless filters[:temperature].blank?
      drinks = drinks.where(temperature: filters[:temperature])
    end

    drinks.order(:created_at)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @drinks = Drink.order(:name).page params[:page]
    respond_to do |format|
      format.html
      format.js { render action: "list" }
    end
  end

  def simple_filter
    @drinks = Drink.simple_filter(simple_filter_params).page params[:page]
    respond_to do |format|
      format.html { head :no_content }
      format.js { render action: "list" }
    end
  end

  def advanced_filter
    @drinks = Drink.advanced_filter(advanced_filter_params).page params[:page]
    respond_to do |format|
      format.html { head :no_content }
      format.js { render action: "list" }
    end
  end

  protected

    def simple_filter_params
      params.require(:filter).permit(:search)
    end

    def advanced_filter_params
      params.require(:filter).permit(:base_ingredient, :drinkware, :distilled, :origin, :alcohol_level, :temperature, :ibu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def options_for_destilled
    [
      [t(:yes), 0 ],
      [t(:no), 1]
    ]
  end

  def options_for_origin
    Drink.select(:origin).group(:origin).order(:origin).pluck(:origin)
  end
end

app/views/drinks/_advanced_form.html.haml
= form_for :filter, url: advanced_filter_path, remote: true, html: {id: :advanced_filter} do |f|
  %h4.text-center=t(:advanced_form_title)
  .container
    .row
      .col-sm
        = f.text_field :base_ingredient, class: 'form form-control', placeholder: t(:base_ingredient)
      .col-sm
        = f.text_field :drinkware, class: 'form form-control', placeholder:  t(:drinkware)
      .col-sm
        = f.select :distilled, options_for_destilled, {prompt: t(:distilled)}, class: 'form form-control'
      .col-sm
        = f.select :origin, options_for_origin, {prompt: t(:origin)}, class: 'form form-control'
    .row
      .col-sm
        = f.number_field :alcohol_level, min: 0, max: 100, class: 'form form-control', placeholder: t(:alcohol_level), title: t(:alcohol_level)
      .col-sm
        = f.number_field :temperature, min: 0, max: 50, class: 'form form-control', placeholder: t(:temperature), title: t(:temperature)
      .col-sm
        = f.number_field :ibu, min: 0, max: 10, class: 'form form-control', placeholder: t(:ibu), title: t(:ibu)
      .col-sm
        = f.button t(:filter), class: "btn btn-outline-primary", id: 'btn_advanced_filter'

app/views/drinks/_drinks.html.haml
- @drinks.each do |drink|
  .card.drink-card
    = image_tag drink.image_url, class: 'drink-card__img'
    .drink-card__body
      %h2
        = drink.name
      %p
        = drink.description

app/views/drinks/_drinks_list.html.haml
- unless @drinks.blank?
  - @drinks.each do |drink|
    .card.drink-card
      = image_tag drink.image_url, class: 'drink-card__img'
      .drink-card__body
        %h2
          = drink.name
        %p
          = drink.description
  = paginate @drinks, remote: true
- else
  %h3=t('no_results')

app/views/drinks/_simple_form.html.haml
= form_for :filter, url: simple_filter_path, remote: true, html: {id: :simple_filter, class: 'form-inline'} do |f|
  .form-group.mx-sm-3
    = f.text_field :search, class: 'form-control form-control-lg', placeholder: t('try_martini')
  = f.button t(:search), class: "btn btn-outline-primary btn-lg", id: 'btn_simple_filter'

app/views/drinks/index.html.haml
%div
  .header.gradient
    = image_tag 'cocktail-white.svg', class: 'icon'
    .header__title The drinks searcher
  .searcher
    .searcher__radio
      .form-check
        %input#simpleSearch.form-check-input{checked: "checked", name: "searchRadio", type: "radio", value: "simple"}/
        %label.form-check-label{for: "simpleSearch"} Easy search
      .form-check
        %input#advancedSearch.form-check-input{name: "searchRadio", type: "radio", value: "advanced"}/
        %label.form-check-label{for: "advancedSearch"} Recommend me ;)
    .simple-form
      = render partial: 'simple_form'
    .advanced-form
      = render partial: 'advanced_form'

  .drinks-list
    =render 'drinks_list'

app/views/drinks/list.js.erb
$('.drinks-list').html("<%= j render 'drinks/drinks_list' %>");

app/views/drinks/simple_filter.js.erb
$('.drinks-list').html("<%= j render 'drinks/drinks_list' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SumoneDevChallange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>